{"name": "test_valid_sign_up", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x0080DCE3]\n\t(No symbol) [0x007A39D1]\n\t(No symbol) [0x006B4DA8]\n\t(No symbol) [0x006E019F]\n\t(No symbol) [0x006E03AB]\n\t(No symbol) [0x0070EE62]\n\t(No symbol) [0x006FAF14]\n\t(No symbol) [0x0070D57C]\n\t(No symbol) [0x006FACC6]\n\t(No symbol) [0x006D6F68]\n\t(No symbol) [0x006D80CD]\n\tGetHandleVerifier [0x00A83832+2506274]\n\tGetHandleVerifier [0x00AB9794+2727300]\n\tGetHandleVerifier [0x00ABE36C+2746716]\n\tGetHandleVerifier [0x008B6690+617600]\n\t(No symbol) [0x007AC712]\n\t(No symbol) [0x007B1FF8]\n\t(No symbol) [0x007B20DB]\n\t(No symbol) [0x007BC63B]\n\tBaseThreadInitThunk [0x76327D69+25]\n\tRtlInitializeExceptionChain [0x76FFB74B+107]\n\tRtlClearBits [0x76FFB6CF+191]", "trace": "self = <tests.chromeTests.testSignUpModal.TestSignUpModal object at 0x000001538DF7EF50>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"eb37a5bf04880023bfcda7c42b955efa\")>\n\n    @allure.description(\"the test is verify,if user can sign up with valid data\")\n    def test_valid_sign_up(self, driver):\n        self.welcome_to_modal.choose_coktails()\n        assert self.common_actions.get_attribute_by_textcontent(home_lcs[\"person_area_link\"]) == \" התחברות \"\n        self.home_page.sign_in_click()\n        self.sign_up_modal.sign_up_btn_click()\n        self.sign_up_modal.set_phone_number(phone_num)\n        self.sign_up_modal.set_bn_number(f'4030{random.randint(0, 99999)}')\n        self.sign_up_modal.accept_policy()\n        self.sign_up_modal.log_in_btn_click()\n        sleep(3)\n>       self.sign_up_modal.set_1_num(code())\n\ntests\\chromeTests\\testSignUpModal.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc\\pages\\signUpModal.py:35: in set_1_num\n    CommonActions.set_locator(self, sign_up_lcs[\"1input_number_fld\"]).send_keys(num)\nsrc\\utils\\commonActions.py:11: in set_locator\n    return wdw(self.driver, 5).until(ec.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"eb37a5bf04880023bfcda7c42b955efa\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001538DCB3BE0>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       Backtrace:\nE       \t(No symbol) [0x0080DCE3]\nE       \t(No symbol) [0x007A39D1]\nE       \t(No symbol) [0x006B4DA8]\nE       \t(No symbol) [0x006E019F]\nE       \t(No symbol) [0x006E03AB]\nE       \t(No symbol) [0x0070EE62]\nE       \t(No symbol) [0x006FAF14]\nE       \t(No symbol) [0x0070D57C]\nE       \t(No symbol) [0x006FACC6]\nE       \t(No symbol) [0x006D6F68]\nE       \t(No symbol) [0x006D80CD]\nE       \tGetHandleVerifier [0x00A83832+2506274]\nE       \tGetHandleVerifier [0x00AB9794+2727300]\nE       \tGetHandleVerifier [0x00ABE36C+2746716]\nE       \tGetHandleVerifier [0x008B6690+617600]\nE       \t(No symbol) [0x007AC712]\nE       \t(No symbol) [0x007B1FF8]\nE       \t(No symbol) [0x007B20DB]\nE       \t(No symbol) [0x007BC63B]\nE       \tBaseThreadInitThunk [0x76327D69+25]\nE       \tRtlInitializeExceptionChain [0x76FFB74B+107]\nE       \tRtlClearBits [0x76FFB6CF+191]\n\nC:\\Users\\artem\\PycharmProjects\\POMTrado\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "description": "the test is verify,if user can sign up with valid data", "attachments": [{"name": "stdout", "source": "6d5376c7-243a-4d6f-82fe-fa8f1f582e7c-attachment.txt", "type": "text/plain"}], "start": 1680348699388, "stop": 1680348710728, "uuid": "e5d7e67c-10e2-46f9-bbfb-188574f3a094", "historyId": "ae9663723898857d61979df7ef3f015a", "testCaseId": "00b62dc5b156d66426d84991b21a9d0c", "fullName": "tests.chromeTests.testSignUpModal.TestSignUpModal#test_valid_sign_up", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "12616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignUpModal"}]}