{"name": "test_sign_up_invalid_phone_num3", "status": "passed", "description": "the test is verify, that user can't sign up with invalid phone number", "start": 1680369633537, "stop": 1680369634215, "uuid": "8fe121ae-6bfa-4707-895a-388f6e381282", "historyId": "80051cee47059ac718aa3cfe221dd2de", "testCaseId": "98cdbe3a2daee48437d0250a2dccc868", "fullName": "tests.chromeTests.testSignUpModal.TestSignUpModal#test_sign_up_invalid_phone_num3", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "8896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testSignUpModal"}]}