{"name": "test_invalid_purchase_saved_in_db", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x00EFDCE3]\n\t(No symbol) [0x00E939D1]\n\t(No symbol) [0x00DA4DA8]\n\t(No symbol) [0x00DD019F]\n\t(No symbol) [0x00DD03AB]\n\t(No symbol) [0x00DFEE62]\n\t(No symbol) [0x00DEAF14]\n\t(No symbol) [0x00DFD57C]\n\t(No symbol) [0x00DEACC6]\n\t(No symbol) [0x00DC6F68]\n\t(No symbol) [0x00DC80CD]\n\tGetHandleVerifier [0x01173832+2506274]\n\tGetHandleVerifier [0x011A9794+2727300]\n\tGetHandleVerifier [0x011AE36C+2746716]\n\tGetHandleVerifier [0x00FA6690+617600]\n\t(No symbol) [0x00E9C712]\n\t(No symbol) [0x00EA1FF8]\n\t(No symbol) [0x00EA20DB]\n\t(No symbol) [0x00EAC63B]\n\tBaseThreadInitThunk [0x76327D69+25]\n\tRtlInitializeExceptionChain [0x76FFB74B+107]\n\tRtlClearBits [0x76FFB6CF+191]", "trace": "self = <tests.dbTests.test_DB.TestDB object at 0x000001EE6AC8B700>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"7412eb578c485fbb04187736e8dd142b\")>\n\n    @allure.description(\"the test is verify, that invalid purchase didn't saved in db\")\n    def test_invalid_purchase_saved_in_db(self, driver):\n        self.sign_in_modal.sign_in()\n        self.product_page.add_1item()\n        self.cart_bar.check_out_btn_click()\n        self.delivery_details_section.complete_purchase_btn_click()\n>       self.payments_methods_section.purchase_btn_click()\n\ntests\\dbTests\\test_DB.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc\\pages\\paymentsMethodsSection.py:15: in purchase_btn_click\n    CommonActions.click_on_visible_locator_ac(self, payments_mthds_lcs[\"purchase\"])\nsrc\\utils\\commonActions.py:16: in click_on_visible_locator_ac\n    element = wdw(self.driver, 5).until(ec.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"7412eb578c485fbb04187736e8dd142b\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001EE6AF1BE20>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       Backtrace:\nE       \t(No symbol) [0x00EFDCE3]\nE       \t(No symbol) [0x00E939D1]\nE       \t(No symbol) [0x00DA4DA8]\nE       \t(No symbol) [0x00DD019F]\nE       \t(No symbol) [0x00DD03AB]\nE       \t(No symbol) [0x00DFEE62]\nE       \t(No symbol) [0x00DEAF14]\nE       \t(No symbol) [0x00DFD57C]\nE       \t(No symbol) [0x00DEACC6]\nE       \t(No symbol) [0x00DC6F68]\nE       \t(No symbol) [0x00DC80CD]\nE       \tGetHandleVerifier [0x01173832+2506274]\nE       \tGetHandleVerifier [0x011A9794+2727300]\nE       \tGetHandleVerifier [0x011AE36C+2746716]\nE       \tGetHandleVerifier [0x00FA6690+617600]\nE       \t(No symbol) [0x00E9C712]\nE       \t(No symbol) [0x00EA1FF8]\nE       \t(No symbol) [0x00EA20DB]\nE       \t(No symbol) [0x00EAC63B]\nE       \tBaseThreadInitThunk [0x76327D69+25]\nE       \tRtlInitializeExceptionChain [0x76FFB74B+107]\nE       \tRtlClearBits [0x76FFB6CF+191]\n\nC:\\Users\\artem\\PycharmProjects\\POMTrado\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "description": "the test is verify, that invalid purchase didn't saved in db", "start": 1680536634508, "stop": 1680536643674, "uuid": "47337bb9-e50a-4d8a-b48f-0cd58e2ad823", "historyId": "ff0d64df04bf53632d2fbbff1f5c28a3", "testCaseId": "83c533c4201a163ad88783470e358706", "fullName": "tests.dbTests.test_DB.TestDB#test_invalid_purchase_saved_in_db", "labels": [{"name": "parentSuite", "value": "tests.dbTests"}, {"name": "suite", "value": "test_DB"}, {"name": "subSuite", "value": "TestDB"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.dbTests.test_DB"}]}