{"name": "test_execute_invalid_purchase5", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nBacktrace:\n\t(No symbol) [0x0080DCE3]\n\t(No symbol) [0x007A39D1]\n\t(No symbol) [0x006B4DA8]\n\t(No symbol) [0x006E019F]\n\t(No symbol) [0x006E03AB]\n\t(No symbol) [0x0070EE62]\n\t(No symbol) [0x006FAF14]\n\t(No symbol) [0x0070D57C]\n\t(No symbol) [0x006FACC6]\n\t(No symbol) [0x006D6F68]\n\t(No symbol) [0x006D80CD]\n\tGetHandleVerifier [0x00A83832+2506274]\n\tGetHandleVerifier [0x00AB9794+2727300]\n\tGetHandleVerifier [0x00ABE36C+2746716]\n\tGetHandleVerifier [0x008B6690+617600]\n\t(No symbol) [0x007AC712]\n\t(No symbol) [0x007B1FF8]\n\t(No symbol) [0x007B20DB]\n\t(No symbol) [0x007BC63B]\n\tBaseThreadInitThunk [0x76327D69+25]\n\tRtlInitializeExceptionChain [0x76FFB74B+107]\n\tRtlClearBits [0x76FFB6CF+191]", "trace": "self = <tests.chromeTests.testCheckoutProcess.TestCheckoutProcess object at 0x000001538DF7D4E0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"708cfbc59a475b8933b104cd05e86fb2\")>\n\n    @allure.description(\"the test is verify, that user can't execute a purchase with invalid b2b data \")\n    def test_execute_invalid_purchase5(self, driver):\n        self.sign_in_modal.sign_in()\n        self.product_page.add_1item()\n        self.cart_bar.check_out_btn_click()\n        assert driver.current_url == \"https://qa.trado.co.il/checkout\"\n        assert self.common_actions.get_attribute_by_class(deli_dtls_lcs[\"deliv_details_status\"]) \\\n               == \"orderTimeline_time orderTimeline_current orderTimeline_current \"\n        assert self.common_actions.get_attribute_by_value(deli_dtls_lcs[\"bn_num_fld\"]) == \"12345678999\"\n        self.delivery_details_page.set_invoice_details(\"Pizza Jon\", \"12345678999\", \"jhongrey89@mail.com\", \"Paris\",\n                                                       \"Baget\", \"3\", \"a\", \"2\")\n        self.delivery_details_page.complete_purchase_btn_click()\n        self.payments_methods_page.b2b_click()\n>       assert self.common_actions.get_attribute_by_class(\n            home_lcs[\"modal_open\"]) == \"modal_modalWrapper false modal_open    \"\n\ntests\\chromeTests\\testCheckoutProcess.py:415: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc\\utils\\commonActions.py:34: in get_attribute_by_class\n    attribute = wdw(self.driver, 5).until(ec.visibility_of_element_located(locator)).get_attribute(\"class\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"708cfbc59a475b8933b104cd05e86fb2\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000001538E02EB00>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       Backtrace:\nE       \t(No symbol) [0x0080DCE3]\nE       \t(No symbol) [0x007A39D1]\nE       \t(No symbol) [0x006B4DA8]\nE       \t(No symbol) [0x006E019F]\nE       \t(No symbol) [0x006E03AB]\nE       \t(No symbol) [0x0070EE62]\nE       \t(No symbol) [0x006FAF14]\nE       \t(No symbol) [0x0070D57C]\nE       \t(No symbol) [0x006FACC6]\nE       \t(No symbol) [0x006D6F68]\nE       \t(No symbol) [0x006D80CD]\nE       \tGetHandleVerifier [0x00A83832+2506274]\nE       \tGetHandleVerifier [0x00AB9794+2727300]\nE       \tGetHandleVerifier [0x00ABE36C+2746716]\nE       \tGetHandleVerifier [0x008B6690+617600]\nE       \t(No symbol) [0x007AC712]\nE       \t(No symbol) [0x007B1FF8]\nE       \t(No symbol) [0x007B20DB]\nE       \t(No symbol) [0x007BC63B]\nE       \tBaseThreadInitThunk [0x76327D69+25]\nE       \tRtlInitializeExceptionChain [0x76FFB74B+107]\nE       \tRtlClearBits [0x76FFB6CF+191]\n\nC:\\Users\\artem\\PycharmProjects\\POMTrado\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "description": "the test is verify, that user can't execute a purchase with invalid b2b data ", "start": 1680348276656, "stop": 1680348286633, "uuid": "6c53fb28-fbb5-4b76-adf9-0d7daa181994", "historyId": "8494aa55a511269313f24982683c700e", "testCaseId": "babd4359c5f09cfe60c990e0dc592923", "fullName": "tests.chromeTests.testCheckoutProcess.TestCheckoutProcess#test_execute_invalid_purchase5", "labels": [{"name": "parentSuite", "value": "tests.chromeTests"}, {"name": "suite", "value": "testCheckoutProcess"}, {"name": "subSuite", "value": "TestCheckoutProcess"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "12616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.chromeTests.testCheckoutProcess"}]}