{"name": "test_sign_up_invalid_bn_number1", "status": "passed", "description": "the test is verify, that user can't sign up with invalid business number", "start": 1680536577995, "stop": 1680536580373, "uuid": "48c587c4-288f-49e6-80d3-8101bf0d8ddf", "historyId": "58dc2da6d305e42fa39200ddc9413c99", "testCaseId": "321528b1e0222f2a55616de043529329", "fullName": "tests.edgeTests.testSignUpModal.TestSignUpModal#test_sign_up_invalid_bn_number1", "labels": [{"name": "parentSuite", "value": "tests.edgeTests"}, {"name": "suite", "value": "testSignUpModal"}, {"name": "subSuite", "value": "TestSignUpModal"}, {"name": "host", "value": "krot"}, {"name": "thread", "value": "19772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.edgeTests.testSignUpModal"}]}